AsteroidOS/meta-smartwatch

meta-narwhal/recipes-android/android-init/android-init/init.rc
It seems that the permission to execute is also needed for all users to have control of the hands. This fixes this. This change is necessary for the PhysicalHands module  (an extension of qml-asteroid to support the physical hands, which I will upstream very soon) to work
=> Fix permissions for hands

meta-sparrow/conf/machine/sparrow.conf, meta-sparrow/recipes-core/psplash/psplash_git.bbappend
This automatically loads the kernel module needed to expose a WiFi interface, but it's still disabled/soft-blocked by default (this is good, it means that it doesn't scan for WiFi access points by default).
Additionally, adjust the animated bootlogo so that it matches the screen resolution. This should lead to a clean transition from the bootlogo to the splash animation in the launcher.
Thanks to @eLtMosen for testing these things :smile:
=> Load WiFi kernel module and adjust bootlogo size

meta-catfish/recipes-android/android-init/android-init/init.rc
We have had 2 catfish have nanohub bricked so far. Not updating nanohub seems to have no side effects, so it's safer to leave that microcontroller alone until we figure out what's actually causing this issue.
Both of the issues happened on devices that were dual-booted, but we can't be sure that this won't happen on a full flash.
=> Removed service updating nanohub from init.rc

meta-narwhal/recipes-android/android/android/audio_policy.conf, meta-narwhal/recipes-android/android/android_narwhal-n.bb, meta-narwhal/recipes-multimedia/pulseaudio/pulseaudio/default.pa, meta-narwhal/recipes-multimedia/pulseaudio/pulseaudio_%.bbappend
Add a custom audio policy configuration file that removes invalid entries such that the module-droid-card can successfully load it.
This fixes the microphone on `narwhal`.
=> narwhal: Fix micropone.

meta-catfish/recipes-nemomobile/mce/mce/builtin-gconf.values, meta-catfish/recipes-nemomobile/mce/mce_%.bbappend, meta-narwhal/recipes-nemomobile/mce/mce/builtin-gconf.values, meta-narwhal/recipes-nemomobile/mce/mce_%.bbappend
These watches have some other way to display the time when the screen is off (Additional LCD or physical hands).
Hence we don't need to have Always-on-Display enabled by default. This obviously improves the battery life since the SoC doesn't need to be awakened every minute.
=> Disable Always-on-Display on catfish and narwhal by default.

meta-skipjack/recipes-core/bluebinder/bluebinder.bbappend, meta-skipjack/recipes-core/bluebinder/bluebinder/0001-service-fixes.patch
Recent versions of Bluebinder rely on rfkill [^1].
Skipjack does not expose an /dev/rfkill device causing bluebinder to fail.
A probable more maintainable method would be to either:
- Provide two versions of `bluebinder`: `bluebinder-rfkill`, `bluebinder-no-rfkill`.
- Disable `rfkill` support at runtime by patching `bluebinder`.
This fixes https://github.com/AsteroidOS/asteroid/issues/216 and the bluetooth issue mentioned in https://github.com/AsteroidOS/asteroid/issues/212
[^1]: https://github.com/mer-hybris/bluebinder/pull/21
=> skipjack: bluebinder: Downgrade bluebinder to fix Bluetooth.

meta-tetra/recipes-android/android-init/android-init/init.rc
Finally found a solution to the battery drain issue on `tetra`!
The solution is embarrassingly simple too!
Battery life has improved from barely making it up to 8 hours to an entire day of use with only ~25% drained.
I wasn't sure if it would work with AOD since we don't actually blank the display. But it looks like the PMU handles this perfectly.
I did notice that Bluetooth did become less reliable after this change. Removing the BLE only mode made it more reliable, so we could apply https://github.com/AsteroidOS/meta-smartwatch/commit/85e529c615f87f4cd8c923116b6d37e0059b2f12 here too.
This fixes https://github.com/AsteroidOS/meta-smartwatch/issues/35.
=> tetra: android-init: Initialize the PMU.

meta-tetra/recipes-asteroid/asteroid-launcher/asteroid-launcher/default.conf
`tetra` along with many other ports suffer from broken fonts due to a miscompilation in libc.so (from Android).
This results in broken fonts. Qt enables said workaround by default on Android builds but as we are building for Linux this isn't applied.
One can enable it at runtime via a environment variable.
Ref: https://bugreports.qt.io/browse/QTBUG-34984
=> tetra: asteroid-launcher: Enable glyph workaround to fix font rendering issue.

meta-sturgeon/recipes-nemomobile/sensorfw/sensorfw-hybris-hal-plugins_%.bbappend, meta-sturgeon/recipes-nemomobile/sensorfw/sensorfw/0002-HybrisHrmAdaptor-Set-default-delay-to-200-ms.patch
The previous method no longer appears to work with recent versions of `sensorfw`.
Instead of setting the interval a single time, set it as a default to prevent it from setting the interval to zero.
This fixes an issue where the heart rate sensor would only start once during a boot.
I initially considered updating the existing patch (https://github.com/AsteroidOS/meta-asteroid/blob/master/recipes-nemomobile/sensorfw/files/0002-Add-heart-rate-monitor-sensor-with-hybris-adaptor.patch) but decided against that as this issue is specific to `sturgeon` other watches do not appear to have this issue. But admittedly since the original patch existed for a long time we cannot be entirely sure about that.
This fixes https://github.com/AsteroidOS/meta-smartwatch/issues/82.
=> sturgeon: sensorfw: Set default interval for the heart rate sensor.

meta-narwhal/recipes-android/android-init/android-init/init.rc
AsteroidOS does not use time zones but WearOS does. This means that WearOS could store the current time including the timezone on physical hands module. Restoring the time on AsteroidOS from the physical hands would cause for an offset in hours as part of the timezone incompatibility. Setting it to zero fixes this until we have proper support for time zones in AsteroidOS.
=> narwhal: Set timezone to zero to fix a synchronization issue.

meta-minnow/recipes-kernel/linux/linux-minnow/0002-dtcat-Port-to-Python-3.patch
I've seen 3 approaches by distros concerning `python`
- It points to the newest python version
- It points to the latest (now EOL) version of python2
- It doesn't exist
The file is compatible with Python 3 and should therefore declare `python3` explicitly in the shebang.
With this minor patch, we don't depend on either `python2.7` being present or a `python-is-python3` package.
=> Specify python version in 0002-dtcat-Port-to-Python-3.patch

meta-beluga/recipes-android/android-init/android-init/init.rc, meta-beluga/recipes-navigation/geoclue/geoclue_%.bbappend
This adds the necessary service and backend such that GPS works on `beluga`.
=> beluga: Add support for GPS.

meta-beluga/conf/machine/beluga.conf, meta-beluga/recipes-android/android-init/android-init/init.rc, meta-beluga/recipes-nemomobile/nfcd/nfcd_git.bbappend
The time isn't saved to the RTC on `beluga` so we need to use `swclock-offset` to fix this (https://github.com/AsteroidOS/meta-asteroid/pull/121).
Additionally, add the binder runtime dependency to nfcd allowing us to use NFC tags on `beluga`.
=> beluga: Enable NFC daemon and fix time after boot.

meta-tetra/recipes-android/android/android_tetra-mm.bb
This is necessary, otherwise the -dev package cannot be installed in generated SDKs, since the -dev package depends on the main one.
=> tetra: android: Allow for empty main package

meta-wren/conf/machine/wren.conf
This fixes the following warnings:
```
WARNING: preferred version lollipop of android not available (for item android-system)
WARNING: versions of android available: marshmallow msm8909+pie msm8909w+pie
WARNING: preferred version lollipop of android not available (for item android)
WARNING: versions of android available: marshmallow msm8909+pie msm8909w+pie
WARNING: preferred version lollipop of android not available (for item android-dev)
WARNING: versions of android available: marshmallow msm8909+pie msm8909w+pie
WARNING: preferred version lollipop of android not available (for item virtual/android-headers)
WARNING: versions of android available: marshmallow msm8909+pie msm8909w+pie
```
=> wren: Correct preferred android version.

meta-ray/recipes-core/libhybris/libhybris/0001-hybris-egl-Provide-eglCreatePlatformWindowSurface.patch, meta-ray/recipes-core/libhybris/libhybris_git.bbappend
Since  https://github.com/libhybris/libhybris/commit/a1bf776f4c06caba8078c7335deb766b3a77fdf1 the eglGetPlatformDisplay() function has been implemented. This function is part of EGL 1.5. Some platforms rely on the existence of this function to detect if EGL 1.5 is supported [^1]. However, libhybris does not implement all EGL 1.5 functions, this provides the implementation for the eglCreatePlatformWindowSurface() function to fix a compilation issue with Qt [^2].
It's worth noting that the eglCreatePlatformWindowSurface() function and the eglCreateWindowSurface() function are not identical. Similar to https://github.com/libhybris/libhybris/commit/362efd97cd5b18f580c402d3fc14555f1ef6e31e we might need to implement additional type conversions at a later stage.
[^1]: …
=> ray: libhybris: Fix compilation.

meta-anthias/conf/machine/anthias.conf, meta-bass/conf/machine/bass.conf, meta-beluga/conf/machine/beluga.conf, meta-catfish/conf/machine/catfish.conf, meta-dory/conf/machine/dory.conf, meta-lenok/conf/machine/lenok.conf, meta-minnow/conf/machine/minnow.conf, meta-mooneye/conf/machine/mooneye.conf, meta-mtk6580/conf/machine/harmony.conf, meta-mtk6580/conf/machine/inharmony.conf, meta-narwhal/conf/machine/narwhal.conf, meta-nemo/conf/machine/nemo.conf, meta-pike/conf/machine/pike.conf, meta-ray/conf/machine/firefish.conf, meta-ray/conf/machine/ray.conf, meta-sawfish/conf/machine/sawfish.conf, meta-skipjack/conf/machine/skipjack.conf, meta-smelt/conf/machine/smelt.conf, meta-sparrow/conf/machine/sparrow.conf, meta-sprat/conf/machine/sprat.conf, meta-sturgeon/conf/machine/sturgeon.conf, meta-swift/conf/machine/swift.conf, meta-tetra/conf/machine/tetra.conf, meta-wren/conf/machine/wren.conf
Since the processor tune is machine specific, it should be set in the same place where the architecture is defined.
this accompanies and should be merged before https://github.com/AsteroidOS/meta-asteroid/pull/132
=> Move defaulttune from meta-asteroid hybris-watch.inc to machine-specific conf files.

meta-pike/recipes-android/android-init/android-init/init.rc, meta-pike/recipes-navigation/geoclue/geoclue_%.bbappend
As the title says, this starts the GPS daemon and ensures that the HAL backend is used for geoclue.
This fixes GPS on `pike`.
=> pike: Fix GPS

meta-koi/recipes-core/psplash/psplash_git.bbappend
this reverts a change made in efc3b0c7, where the psplash double buffering patch was removed. The patch prevents a momentary display corruption as psplash stops and asteroid-launcher starts.
I failed to notice this during testing, as the corruption is very brief. After some far more rigorous testing, I can confirm that the display corruption reliably happens without the patch, and is definitely fixed by the patch.
=> Koi: psplash: add double buffering patch

meta-catfish/conf/machine/catfish.conf
The time isn't saved to the RTC on `catfish` so we need to use `swclock-offset` to fix this.
This fixes #68.
=> catfish: Install swclock-offset.

meta-koi/recipes-android/android/android_koi-o.bb
https://github.com/AsteroidOS/meta-smartwatch/commit/efc3b0c7ad9db17ae660dae513a03157294ecd08 removed the `audio_policy.conf` file as audio isn't working anyways. Yet, the recipe still tries to install this non-existing file.
=> koi: android: Do not try to install audio_policy.conf.

meta-narwhal/conf/machine/narwhal.conf, meta-narwhal/recipes-android/android-init/android-init/init.rc, meta-narwhal/recipes-core/hands-timesync/hands-timesync.bb
despite this existing as an asteroid repo for over a year now, it's not actually been added as a recipe. I think this is a sign of anti-narwhal prejudice. 
This adds the recipe, and adds it to the narwhal image. 
it also removes the tz_minutes reset from init.rc: This was previously needed to make sure that the time would not change between reboots when it was being read back from the hands controller on bootup. This is no longer relevant, as asteroid now supports timezones (so the 0 reset would actually be harmful) and hands-timesync takes care of setting this value correctly.
It is worth checking how I've got the systemd units set up here. Unlike catfish and ayu, where the LCDs only display the time, the time set to the hands will be written to the main system after a reboot. For this …
=> narwhal: Add hands-timesync

meta-sturgeon/recipes-nemomobile/sensorfw/sensorfw/0001-HybrisStepCounterAdapter-Set-delay-to-normal-speed.patch
The previous method no longer appears to work with recent versions of sensorfw. Instead of setting the interval a single time, set it as a default to prevent it from setting the interval to zero.
This commit is based on https://github.com/AsteroidOS/meta-smartwatch/commit/9460f010c90ced0a34a4b574651f551ede679737.
=> sturgeon: sensorfw: Set default interval for the step counter.

meta-hoki/conf/machine/hoki.conf
This fixes an issue where the wrong android version could be used.
It was supposed to be fixed as part of: https://github.com/AsteroidOS/meta-smartwatch/pull/178
=> hoki: Prefer armv7+pie64.

meta-koi/recipes-android/android-init/android-init/init.rc
This is needed for ceres to be able to set time and change settings on the LCD.
=> koi: set permissions for LCD in init.rc

meta-sawfish/recipes-kernel/linux/linux-sawfish/00011-dts-sawshark-Remove-USB-gadget-function-list.patch, meta-sawfish/recipes-kernel/linux/linux-sawfish_n.bb
Instead use the default list provided by the android gadget driver.
Essentially it adds rndis mode to the supported functions list, fixing SSH mode.
=> sawfish: linux-sawfish: Remove USB gadget function list.

meta-ray/conf/machine/firefish.conf, meta-ray/conf/machine/ray.conf, meta-skipjack/conf/machine/skipjack.conf, meta-swift/conf/machine/swift.conf
This depends on https://github.com/AsteroidOS/meta-asteroid/pull/177
=> firefish/ray/skipjack/swift: Rename wifi-enabler to msm-wifi-enabler.

meta-anthias/recipes-kernel/linux/linux-anthias_mm-dr1.bb, meta-bass/recipes-kernel/linux/linux-bass_lp-mr1.bb, meta-beluga/recipes-kernel/linux/linux-beluga_p.bb, meta-catfish/recipes-kernel/linux/linux-catfish_p.bb, meta-dory/recipes-kernel/linux/linux-dory_mm.bb, meta-koi/recipes-kernel/linux/linux-koi_o.bb, meta-lenok/recipes-kernel/linux/linux-lenok_mm-mr1.bb, meta-mooneye/recipes-kernel/linux/linux-mooneye_o.bb, meta-mtk6580/recipes-kernel/linux/linux-harmony_lp-mr1.bb, meta-narwhal/recipes-kernel/linux/linux-narwhal_n.bb, meta-nemo/recipes-kernel/linux/linux-nemo_lp-mr1.bb, meta-pike/recipes-kernel/linux/linux-pike_o.bb, meta-ray/recipes-kernel/linux/linux-firefish_o.bb, meta-ray/recipes-kernel/linux/linux-ray_n.bb, meta-sawfish/recipes-kernel/linux/linux-sawfish_n.bb, meta-skipjack/recipes-kernel/linux/linux-skipjack_o.bb, meta-smelt/recipes-kernel/linux/linux-smelt_mm-mr1.bb, meta-sparrow/recipes-kernel/linux/linux-sparrow-mainline_6.0.bb, meta-sparrow/recipes-kernel/linux/linux-sparrow_mm-mr1.bb, meta-sprat/recipes-kernel/linux/linux-sprat_mm-dr1.bb, meta-sturgeon/recipes-kernel/linux/linux-sturgeon_mm-mr1.bb, meta-swift/recipes-kernel/linux/linux-swift_mm-mr1.bb, meta-tetra/recipes-kernel/linux/linux-tetra_mm-dr1.bb, meta-wren/recipes-kernel/linux/linux-wren_mm-mr1.bb
BOOT_PARTITION is not used in any recipe, remove it for all platforms.
This was identified by @FlorentRevest, thanks :smile:
=> Remove usage of BOOT_PARTITION.

meta-mtk6580/recipes-android/android/android_harmony-lp.bb
The `include` directory in the tarball only contains the droidmedia headers.
3fccd3f605f4746e2abd123b6caa0083fcadcbe6 removed these headers from the extracted tarball, then it copies this to the destination directory.
However this introduces an issue when `do_install` is called multiple times since it can't delete the headers anymore (they don't exist).
=> mtk6580: android: Don't install include headers.

meta-dory/recipes-kernel/linux/linux-dory/0008-random-introduce-getrandom-2-system-call.patch, meta-dory/recipes-kernel/linux/linux-dory/0009-ARM-wire-up-getrandom-syscall.patch, meta-dory/recipes-kernel/linux/linux-dory_mm.bb, meta-sturgeon/recipes-kernel/linux/linux-sturgeon/0011-random-introduce-getrandom-2-system-call.patch, meta-sturgeon/recipes-kernel/linux/linux-sturgeon/0012-ARM-wire-up-getrandom-syscall.patch, meta-sturgeon/recipes-kernel/linux/linux-sturgeon_mm-mr1.bb
This is based on @MagneFire's excellent work in backporting random.c changes in the kernel to kernel version 3.10.  Note that this only addresses `dory` and `sturgeon` because those are the only two kernl version 3.10 watches I have available to test.  
This relates to https://github.com/AsteroidOS/asteroid/issues/245 to allow us to move from `kirkstone` to `mickledore`.
=> Update dory and sturgeon

meta-hoki/conf/machine/hoki.conf, meta-hoki/recipes-android/android-init/android-init/init.rc, meta-hoki/recipes-kernel/modules/linux-audio-modules-hoki/0001-Remove-export-from-Kbuild-files.patch, meta-hoki/recipes-kernel/modules/linux-audio-modules-hoki/0002-Avoid-shell-expansion-in-recursively-expanded-variab.patch, meta-hoki/recipes-kernel/modules/linux-audio-modules-hoki/0003-Import-beluga-makefile.patch, meta-hoki/recipes-kernel/modules/linux-audio-modules-hoki/0003-Remove-export-from-Kbuild-files.patch, meta-hoki/recipes-kernel/modules/linux-audio-modules-hoki/0004-Ignore-compilation-warnings.patch, meta-hoki/recipes-kernel/modules/linux-audio-modules-hoki/0005-dsp-Compile-codecs-for-out-of-tree-builds.patch, meta-hoki/recipes-kernel/modules/linux-audio-modules-hoki_p.bb
Provides the audio kernel modules to allow booting the modem.
Then start the required Android services to get sensors to work.
Audio isn't functional at this point, I suspect that this is because the Android R firmware is loaded on an Android Pie base, which may require a different audio routing.
This depends on https://github.com/AsteroidOS/meta-asteroid/pull/182.
This solves #185.
=> hoki: Fix sensors

meta-anthias/recipes-asteroid/asteroid-launcher/asteroid-launcher-configs/default.conf, meta-anthias/recipes-asteroid/asteroid-launcher/asteroid-launcher-configs_%.bbappend, meta-lenok/recipes-asteroid/asteroid-launcher/asteroid-launcher-configs/default.conf, meta-lenok/recipes-asteroid/asteroid-launcher/asteroid-launcher-configs_%.bbappend, meta-sparrow/recipes-asteroid/asteroid-launcher/asteroid-launcher-configs/default.conf, meta-sparrow/recipes-asteroid/asteroid-launcher/asteroid-launcher-configs_%.bbappend, meta-sprat/recipes-asteroid/asteroid-launcher/asteroid-launcher-configs/default.conf, meta-sprat/recipes-asteroid/asteroid-launcher/asteroid-launcher-configs_%.bbappend, meta-wren/recipes-asteroid/asteroid-launcher/asteroid-launcher-configs/default.conf, meta-wren/recipes-asteroid/asteroid-launcher/asteroid-launcher-configs_%.bbappend
https://github.com/AsteroidOS/meta-asteroid/commit/967c9afa70240cbdaf6dd28465e3b74d361f6d1d removed  the default configuration, requiring a machine specific configuration for hybris devices.
This provides the configuration needed for `anthias`, `lenok`, `sparrow`, `sprat` and`wren`.
This fixes https://github.com/AsteroidOS/meta-smartwatch/issues/240.
=> anthias, lenok, sparrow, sprat, wren: asteroid-launcher-configs: Provide device configuration.

meta-hoki/recipes-android/android-init/android-init/init.rc, meta-hoki/recipes-nemomobile/libnci/libncicore/libncicore.conf, meta-hoki/recipes-nemomobile/libnci/libncicore_git.bbappend
Starts the needed NFC Android daemon and provides a configuration such that NFC works.
The NFC daemon is disabled, but manually starting it is enough to get it to work.
On `hoki` graphical issues are also observed when scanning a tag (similar to https://github.com/AsteroidOS/meta-asteroid/pull/178).
=> hoki: Fix NFC.

meta-sparrow/recipes-kernel/linux/linux-sparrow-mainline/0001-ata-ahci-fix-enum-constants-for-gcc-13.patch, meta-sparrow/recipes-kernel/linux/linux-sparrow-mainline_6.0.bb
gcc-13 slightly changes the type of constant expressions that are defined in an enum, which triggers a compile time sanity check in libata:
linux/drivers/ata/libahci.c: In function 'ahci_led_store': linux/include/linux/compiler_types.h:357:45: error: call to '__compiletime_assert_302' declared with attribute error: BUILD_BUG_ON failed: sizeof(_s) > sizeof(long) 357 | _compiletime_assert(condition, msg, __compiletime_assert_, __COUNTER__)
The new behavior is that sizeof() returns the same value for the constant as it does for the enum type, which is generally more sensible and consistent.
The problem in libata is that it contains a single enum definition for lots of unrelated constants, some of which are large positive (unsigned) integers like 0xffffffff, while others like (1<<31) are …
=> sparrow-mainline: linux: ata: ahci: fix enum constants for gcc-13

meta-hoki/recipes-core/initrdscripts/initramfs-scripts-android/init.machine.sh
This shows the AsteroidOS logo and checks to see if AsteroidOS is already present.  If it isn't we start the ADB daemon and tell the user to flash the ext4 image.  If it is present, the user has five seconds to press the middle button.  If the user presses the middle button during those 5 seconds, we start the ADB daemon; othewise it just boots normally.
=> Provide a means to easily reflash AsteriodOS

meta-beluga/recipes-core/initrdscripts/initramfs-scripts-android/init.machine.sh
This change is analogous to https://github.com/AsteroidOS/meta-smartwatch/pull/254/files.
However, on `beluga` only the bottom right button is sending an event so this is used.
=> beluga: initrdscripts: Provide a means to access ADB from the boot image

meta-beluga/recipes-core/initrdscripts/initramfs-scripts-android_1.0.bbappend
Without this, a Yocto Scarthgap build will fail with and installed-vs-shipped QA issue because init.machines is not automatically added to ${PN}.
=> beluga: initrdscripts: Add init.machine to main package

meta-triggerfish/recipes-kernel/linux/linux-triggerfish/0005-initramfs-Don-t-skip-initramfs.patch, meta-triggerfish/recipes-kernel/linux/linux-triggerfish_p.bb
Patch and direction by @MagneFire, this gets `triggerfish` to a booting (albeit poor) state. Tested with a Fossil 5 Julianna.
=> triggerfish: Include hoki initramfs patch

meta-triggerfish/conf/machine/triggerfish.conf, meta-triggerfish/recipes-core/base-files/base-files/fstab, meta-triggerfish/recipes-core/base-files/base-files_%.bbappend, meta-triggerfish/recipes-kernel/make-mod-scripts/make-mod-scripts_%.bbappend, meta-triggerfish/recipes-kernel/modules/linux-wlan-modules-triggerfish/wlan-module-load.service, meta-triggerfish/recipes-kernel/modules/linux-wlan-modules-triggerfish_p.bb
This commit adds basic wifi functionality to the fossil gen 5 triggerfish in order for configuration via connman / wpa_supplicant to work.
To do that firmware blobs are now mounted at the correct location where they can be found via firmwared.
An external kernel module 'wlan' to provide the interface is included and loaded at startup
Enjoy :D
=> triggerfish: Add basic wifi support
